# Generated by Django 5.2.7 on 2025-10-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории доп. услуг')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория доп. услуг',
                'verbose_name_plural': 'Категории доп. услуг',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(help_text='Заполняется автоматически, используется для красивых ссылок.', unique=True, verbose_name='URL (автоматически)')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание (для карточек)')),
                ('price_display', models.CharField(help_text="Например: 'от 140 ₽/м²' или 'от 500 ₽'", max_length=100, verbose_name='Отображаемая цена')),
                ('icon', models.CharField(help_text="Например: 'house_siding' или 'construction'", max_length=100, verbose_name='Иконка (Material Symbols)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='services/hero/', verbose_name="Фоновое изображение ('шапка')")),
                ('full_description', models.TextField(verbose_name='Полное описание услуги')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO Description')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Основные услуги',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название доп. услуги')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.additionalservicecategory')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст пункта')),
                ('category', models.CharField(help_text="Например: 'Жилые комнаты', 'Кухня'", max_length=100, verbose_name='Категория (таб)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='services.service')),
            ],
            options={
                'verbose_name': 'Пункт в чек-листе',
                'verbose_name_plural': 'Пункты в чек-листах',
            },
        ),
    ]
