# Generated by Django 5.2.7 on 2025-10-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=models.TextField(help_text='Основной текст, который будет на странице услуги.', verbose_name='Полное описание услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Будет фоном на странице этой услуги.', null=True, upload_to='services/hero/', verbose_name="Фоновое изображение ('шапка')"),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text="Название иконки с сайта Google Fonts. Пример: 'diamond', 'construction'", max_length=100, verbose_name='Иконка (Material Symbols)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Краткое описание для поисковиков.', verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название услуги.', max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше услуга в списке.', verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_display',
            field=models.CharField(help_text="Пример: 'от 140 ₽/м²' или 'от 500 ₽'", max_length=100, verbose_name='Отображаемая цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(max_length=300, verbose_name='Краткое описание (для карточек на главной)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='Генерируется из названия. Лучше не трогать.', max_length=200, unique=True, verbose_name='URL (автоматически)'),
        ),
    ]
