# Generated by Django 5.2.7 on 2025-10-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_full_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, choices=[('cleaning_services', 'Веник и совок'), ('construction', 'Строительные инструменты'), ('diamond', 'Бриллиант (Генеральная уборка)'), ('house', 'Дом'), ('cottage', 'Коттедж'), ('apartment', 'Квартира'), ('window', 'Окно'), ('chair', 'Кресло (Химчистка)'), ('bug_report', 'Жук (Дезинсекция)'), ('eco', 'Экология'), ('health_and_safety', 'Безопасность')], default='cleaning_services', help_text='Выберите иконку из списка.', verbose_name='Иконка'),
        ),
    ]
