# Generated by Django 5.2.7 on 2025-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='cleaning_services', help_text='Название иконки с сайта Google Fonts.', max_length=100, verbose_name='Иконка'),
        ),
    ]
