# Generated by Django 5.2.7 on 2025-10-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Основной номер телефона')),
                ('work_hours', models.CharField(max_length=100, verbose_name='Часы работы')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для связи')),
                ('vk_link', models.URLField(blank=True, verbose_name='Ссылка на ВКонтакте')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
