# Generated by Django 5.2.7 on 2025-10-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение (детали заявки)'),
        ),
    ]
