# Generated by Django 5.2.7 on 2025-10-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (для фильтра)')),
            ],
            options={
                'verbose_name': 'Категория портфолио',
                'verbose_name_plural': 'Категории портфолио',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок проекта')),
                ('short_description', models.TextField(verbose_name='Краткое описание (для модального окна)')),
                ('preview_image', models.ImageField(upload_to='portfolio/previews/', verbose_name='Главное фото (для карточки)')),
                ('image_before', models.ImageField(upload_to='portfolio/before_after/', verbose_name="Фото 'ДО'")),
                ('area', models.CharField(blank=True, max_length=50, verbose_name='Площадь')),
                ('time_spent', models.CharField(blank=True, max_length=50, verbose_name='Затрачено времени')),
                ('team_size', models.CharField(blank=True, max_length=50, verbose_name='Размер команды')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfoliocategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Проект в портфолио',
                'verbose_name_plural': 'Проекты в портфолио',
                'ordering': ['-date_completed', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/gallery/', verbose_name="Фотография 'ПОСЛЕ'")),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись к фото (необязательно)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_images', to='portfolio.portfolioproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': "Фото 'ПОСЛЕ' для галереи",
                'verbose_name_plural': "Фото 'ПОСЛЕ' для галереи",
            },
        ),
    ]
